# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cntdwn < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satodaiki/cntdwn/releases/download/v0.1.1/cntdwn_Darwin_x86_64.tar.gz"
      sha256 "db6df04cde0fa2facfa18c5aad7787391bd35e8e2bbb7e22b3a9302658d646e4"

      def install
        bin.install "cntdwn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satodaiki/cntdwn/releases/download/v0.1.1/cntdwn_Darwin_arm64.tar.gz"
      sha256 "47587e128bd605a589f198f4beea6411c6b09f0e80773a627ded42633c678e3f"

      def install
        bin.install "cntdwn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satodaiki/cntdwn/releases/download/v0.1.1/cntdwn_Linux_x86_64.tar.gz"
      sha256 "825ea98902cf97daca65d48d37d2317790131a30a0d5c2b293ff7bbd97da6e34"
      def install
        bin.install "cntdwn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satodaiki/cntdwn/releases/download/v0.1.1/cntdwn_Linux_arm64.tar.gz"
      sha256 "b95009b977e2656daa6edc6e94f09aa6bcd2b47be5746163e7e6bf24cf54b5c3"
      def install
        bin.install "cntdwn"
      end
    end
  end
end
